//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Accounting.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Accounting.Resources.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hành động.
        /// </summary>
        public static string Actions {
            get {
                return ResourceManager.GetString("Actions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thêm mới.
        /// </summary>
        public static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bò.
        /// </summary>
        public static string Beef {
            get {
                return ResourceManager.GetString("Beef", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trâu.
        /// </summary>
        public static string Buffalo {
            get {
                return ResourceManager.GetString("Buffalo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lọc.
        /// </summary>
        public static string Filter {
            get {
                return ResourceManager.GetString("Filter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quản lý giá.
        /// </summary>
        public static string Manage_Price {
            get {
                return ResourceManager.GetString("Manage Price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loại thịt.
        /// </summary>
        public static string Meat_Type {
            get {
                return ResourceManager.GetString("Meat Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thịt tươi.
        /// </summary>
        public static string Normal_Meat {
            get {
                return ResourceManager.GetString("Normal Meat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Danh sách mặt hàng.
        /// </summary>
        public static string Product_List {
            get {
                return ResourceManager.GetString("Product List", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quản lý Mặt hàng.
        /// </summary>
        public static string Product_Management {
            get {
                return ResourceManager.GetString("Product Management", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loại hàng.
        /// </summary>
        public static string Product_Type {
            get {
                return ResourceManager.GetString("Product Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đông lạnh.
        /// </summary>
        public static string Prozen_Meat {
            get {
                return ResourceManager.GetString("Prozen Meat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tìm theo tên.
        /// </summary>
        public static string Search_by_name {
            get {
                return ResourceManager.GetString("Search by name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giá Nhập Hôm Nay.
        /// </summary>
        public static string Today_Entry_Price {
            get {
                return ResourceManager.GetString("Today Entry Price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giá Bán Hôm Nay.
        /// </summary>
        public static string Today_Sale_Price {
            get {
                return ResourceManager.GetString("Today Sale Price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giá Nhập Hôm Qua.
        /// </summary>
        public static string Yesterday_Entry_Price {
            get {
                return ResourceManager.GetString("Yesterday Entry Price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giá Bán Hôm Qua.
        /// </summary>
        public static string Yesterday_Sale_Price {
            get {
                return ResourceManager.GetString("Yesterday Sale Price", resourceCulture);
            }
        }
    }
}
